### ISSUE TITLE
Call-function-Prices

### ISSUE THREAD

**Issue by alhoussss** [alhoussss/saladbar#1]
Bonjour Mr,
J'essaie d'appeler ma fonction Prices pour afficher le prix de mes articles mais j'ai une erreur et je ne sais pas à quoi elle est dû.
Pouvez-vous m'aider, Merci.![Capture d’écran 2022-12-22 145743](https://user-images.githubusercontent.com/91543821/209150072-f3e7d9dc-23d6-4fc2-9074-309a638a5041.png)

**Comment by bratosab** [comment]
Bonjour Alhouss,

Désolé de la réponse tardive, je suis de retour aujourd'hui.
Tu as toujours le problème ? je peux regarder dans l'aprem.

Abdallah.

**Comment by alhoussss** [comment]
Bonsoir Mr, non c'est bon !
