### ISSUE TITLE
récuperer-résultat-onclick-boutton correspondant

### ISSUE THREAD

**Issue by alhoussss** [alhoussss/saladbar#4]
Bonjour Mr, j'ai vraiment besoin de votre expertise là.
dans le fichier Order.js, j'essai d'afficher le résultat bu boutton sur lequel on click lorsqu'on veut ajouter des ingrédients.
Pour ça je defini une constante et j'utlise une fonction handclick pour récuperer le résultat mais je n'y arrive pas.
j'ai éssayé pleind'autre option mais ca ne correspond pas au résultat que je souhaite avoir.
Merci !

**Comment by bratosab** [comment]
Hello Alhouss, j'ai récupérer ton projet j'ai du forcer l'install des dépendances... j'ai eu un problème avec google-maps-react, ça fonctionne sans --force chez toi ?
c'est quoi que tu cherche a faire exactement sur le handle click ? j'ai tester l'ajout d'ingrédients a la salade, ça m'affiche un bouton avec 'supprimer' dedans, tu souhaites que ça affiche le nom de l'ingrédient ?

**Comment by bratosab** [comment]
<img width="329" alt="Capture d’écran 2023-01-05 à 11 42 16" src="https://user-images.githubusercontent.com/5938260/210761530-4ee07953-bc18-4b15-bb81-abb7e05329bc.png">
J'ai changé la boucle d'affichage et ça m'affiche maintenant le nom de l'ingrédient 
<img width="295" alt="Capture d’écran 2023-01-05 à 11 43 41" src="https://user-images.githubusercontent.com/5938260/210761747-a7501355-e420-4606-a0e1-1dd5c18a1fd8.png">

**Comment by alhoussss** [comment]
Bonjour Mr, non même lorsque que je fais un --force mon google-maps-react ne s'affiche pas.
ce serait le deuxième problème que je voudrais bien résoudre.
Parfait pour handclick c'etait ça que je voulais merci beaucoup.

**Comment by alhoussss** [comment]
Pourriez-vous commit et push pour que je puisse avoir les changements que vous avez fait pour handclick

**Comment by alhoussss** [comment]
Finalement c'est ok pour handclick, là ce serait juste pour ma maps, si vous pouviez me dire à quoi est dû le bug ce serait parfait :)
